In [1]:
import pandas as pd
from datasets import load_dataset
from utils import counting, mfr, evaluate

# Load data
pub_data = load_dataset("weerayut/multilexnorm2026-pub")

# Select data
lang = "en"
en_train = pub_data["train"].filter(lambda x: x["lang"] == lang)
en_val = pub_data["validation"].filter(lambda x: x["lang"] == lang)

ds = pd.DataFrame(en_val)
ds.head(4)

,raw,norm,lang
0,"[@cdutra5, bruh, get, out, yo, feelings, lol]","[@cdutra5, brother, get, out, your, feelings, ...",en
1,"[rt, @demberel_s, :, manan, dund, xaragdax, te...","[rt, @demberel_s, :, manan, dund, xaragdax, te...",en
2,"[why, dese, niggas, think, dey, doin, summn]","[why, these, niggers, think, they, doing, some...",en
3,"[@tylermajewski, it's, about, more, than, numb...","[@tylermajewski, it's, about, more, than, numb...",en

### Inference

In [2]:
# Smoke test baseline
counts = counting(en_train)
mfr(['bcause', 'u', 'r', 'funny'], counts)

['because', 'you', 'are', 'funny']

In [3]:
ds['pred'] = ds['raw'].apply(lambda x: mfr(x, counts))
ds.head(4)

,raw,norm,lang,pred
0,"[@cdutra5, bruh, get, out, yo, feelings, lol]","[@cdutra5, brother, get, out, your, feelings, ...",en,"[@cdutra5, brother, get, out, you, feelings, lol]"
1,"[rt, @demberel_s, :, manan, dund, xaragdax, te...","[rt, @demberel_s, :, manan, dund, xaragdax, te...",en,"[rt, @demberel_s, :, manan, dund, xaragdax, te..."
2,"[why, dese, niggas, think, dey, doin, summn]","[why, these, niggers, think, they, doing, some...",en,"[why, dese, niggers, think, they, doing, summn]"
3,"[@tylermajewski, it's, about, more, than, numb...","[@tylermajewski, it's, about, more, than, numb...",en,"[@tylermajewski, it's, about, more, than, numb..."

### Evaluate

In [5]:
evaluate(
    raw=ds['raw'].tolist(), 
    gold=ds['norm'].tolist(), 
    pred=ds['pred'].tolist()
)

Baseline acc.(LAI): 93.10
Accuracy:           97.37
ERR:                61.93

(0.9309630275929763, 0.9737157814374523, 0.619273301737757)